python train_one_gpu_prompt.py \
    -dataset_name glas \
    -task_name MedSAM-Prompt \
    -model_type vit_prompt \
    -checkpoint work_dir/SAM/sam_vit_b_01ec64.pth \
    -work_dir ./work_dir \
    -num_epochs 25 \
    -batch_size 2 \
    -train_ratio 0.7 \
    -lr 0.0001 \
    --device cuda:0